config/routes.rb
Rails.application.routes.draw do
  resources :profiles
  resources :cities, only: [:province] do 
    member do 
      get 'province'
    end
  end

  devise_for :users, controllers: {registrations: "registrations"}

  devise_scope :user do
    post '/users/sign_out', to: 'devise/sessions#destroy'
  end

  
  root "home#index"
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :city
  has_one :profile, dependent: :destroy
  has_one :land, dependent: :destroy
  has_one :houses, dependent: :destroy

  validates_presence_of :street, :city
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/city.rb
class City < ApplicationRecord
  belongs_to :province
  has_many :address
  
  validates_presence_of :province, :city_name

  scope :find_cities, ->(province) { where(province_id: province.id)}
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  belongs_to :address
  accepts_nested_attributes_for :address, allow_destroy: true

  validates_presence_of :name_profile, :profile_type, :gender
  validates :phone1, :phone2, presence: true, uniqueness: true

  
  enum gender: { masculine: "MASCULINO", feminine: "FEMININO" }
  enum profile_type: {
    estudante: "ESTUDANTE", 
    professor: "PROFESSOR", 
    funcionario: "FUNCIONARIO"
  }
  
  def self.find_by_user(user) 
    Profile.find_by(user_id: user.id)
  end
  
end

app/models/province.rb
class Province < ApplicationRecord
    has_many :cities
    validates_presence_of :province_name
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_one :profile, dependent: :destroy
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    add_flash_types :info, :error
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController

  def province 
     province = Province.new 
     province.id = params[:id]
     @cities = City.find_cities(province)
    render json: @cities
      
  end
  
   
end

app/controllers/concerns/belongs_another_user_message_concerns.rb
module BelongsAnotherUserMessageConcerns
    extend ActiveSupport::Concern
    
    def belongs_another_user_message(format, house, object_name)
      format.html { redirect_to house_url(house), info: "This #{object_name} belongs to another user." }
      format.json { render json: ["This #{object_name} belongs to another user. Impossible delete"], status: :unprocessable_entity }
    end

end

app/controllers/concerns/profiles_concerns.rb
module ProfilesConcerns
    extend ActiveSupport::Concern
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  before_action :set_profile_by_user_id, only: [ :new, :update ]

  include ProfilesConcerns

  # GET /profiles or /profiles.json
  def index
    @profiles = Profile.includes(:user, :address)
    if current_user.profile.funcionario?
      @profiles = Profile.includes(:user, :address)
    else
      profile = Profile.find_by_user(current_user)
 
      @profiles = []
      @profiles << profile 
    end
  end

  # GET /profiles/1 or /profiles/1.json
  def show
  end

  # GET /profiles/new
  def new

   if !@profile.nil?
      respond_to do |format| 
        format.html { redirect_to profile_url(@profile) }
        format.json { render :show, status: :created, location: @profile}
      end
   else
      @profile = Profile.new
      @profile.build_address
   end
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles or /profiles.json
  def create
    @profile = Profile.new(profile_params)
    @profile.user_id = current_user.id
    
    respond_to do |format|
      if @profile.save
        format.html { redirect_to profile_url(@profile), notice: "Profile was successfully created." }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1 or /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
         
        format.html { redirect_to profile_url(@profile), notice: "Profile was successfully updated." }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1 or /profiles/1.json
  def destroy
    @profile.destroy
    

    respond_to do |format|
      format.html { redirect_to profiles_url(locale: I18n.locale), notice: "Profile was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end
    
    def set_profile_by_user_id 
      @profile ||= Profile.find_by_user_id(current_user.id)
      @profile
    end
    # Only allow a list of trusted parameters through.
    def profile_params
      params.require(:profile).permit(
        :name_profile, 
        :phone1, 
        :phone2, 
        :profile_type, 
        :gender,
        address_attributes: [:id, :street, :city_id, :_destroy] 
      )
    end

end

app/controllers/registrations_controller.rb
# frozen_string_literal: true

class RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  #after_action :create_profile, only: [:create]
  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  #  def create
  #    super
  #  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
   def destroy
     @houses = House.find_houses_by_user(current_user)
     @houses.destroy_all

     @lands = Land.find_lands_by_user(current_user)
     @lands.destroy_all
     super
   end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

 

end

app/helpers/application_helper.rb
module ApplicationHelper
    def cities_array_empty
        city = City.new
        @cities = []
        @cities << city
        @cities
     end
end

app/helpers/city_helper.rb
module CityHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/home/index.html.erb
<br><br><br><br><br><br>
<h1 class="text-center text-success">Projecto de segurança</h1>

app/views/layouts/_about.html.erb
  <section class="text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1>Bumbagora</h1>
        <p class="lead text-success">
Somos uma empresa angolana que nasceu em 2022, atuando na área de desenvolvimento de software, consultoria e vendas gerando valores para os nossos clientes. </p>
        <p>
        <% if !user_signed_in? %>    
          <div class="d-grid gap-2">
            <%= link_to "Criar conta", new_user_registration_path, class: "btn btn-outline-success my-2" %>
          </div>
        <% end %>
        </p>
      </div>
    </div>
  </section>

app/views/layouts/_alert.html.erb
<div class="row d-flex justify-content-center">
    <div class="col-sm-9">
        <div class="alert alert-danger alert-dismissible fade show text-center" role="alert">
        <i class="bi-exclamation-circle-fill" ></i>
        <%= alert %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer mt-auto py-3 bg-light teal-darken-3">
  <p class="text-white text-center"> Conheça o CTO e CIO da empresa.</p>
  <div class="container">
    <ul class="nav justify-content-center">
      <li class="nav-item">
        <a class="nav-link" href="https://twitter.com/PlusVicente"> 
          <i class="bi-twitter footer-icon"></i> 
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="https://github.com/Vicente-jpro"> 
          <i class="bi-github footer-icon"></i>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="https://www.linkedin.com/in/vicente-sim%C3%A3o-504287160/"> 
          <i class="bi-linkedin text-white footer-icon"></i>
        </a>
      </li>
    </ul>
  </div>
  <p class="text-center text-white">
    ©2022 - Bumbagora | Direitos reservados
  </p>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-color bg-warning">

      <div class="container">
        <%= link_to "Projecto de Segurança", root_path, class:"navbar-brand text-white" %> 
        
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          
          <span class=" d-block navbar-toggler-icon"></span>
          <span class=" d-block navbar-toggler-icon"></span>
          <span class=" d-block navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          
            <li class="nav-item">
              <%= link_to "Visualizar perfis", profiles_path, class: "nav-link" %>
            </li>
            <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to "Criar perfil", new_profile_path, class: "nav-link", "data-turbo-frame": "_top" %>
            </li>

            <% end %>
          </ul>
          <ul class="nav justify-content-end ">
          <% if user_signed_in? %>
             
            <li class="nav-item">
            <%= link_to "Segurança", edit_user_registration_path, class: "nav-link"%>
            </li>
              <li class="nav-item ">
              <%= link_to 'Sair', destroy_user_session_path, method: :delete,  class: "nav-link btn btn-outline-light" %>
            </li>
            <% else %>
              <li class="nav-item "> 
              <%= link_to "Criar conta", new_user_registration_path, class: "nav-link " %>
              
            </li>
              <li class="nav-item">
              <%= link_to "Entrar", new_user_session_path, class: "nav-link btn btn-outline-light"%>
            </li>
            <% end %>
        </ul>
        </div>
      </div>
  </nav>
</header>

app/views/layouts/_info.html.erb
<br>
<div class="row d-flex justify-content-center">
    <div class="col-sm-9">
        <div class="alert alert-info alert-dismissible fade show text-center" role="alert">
        <i class="bi-exclamation-circle-fill" ></i>
        <%= info %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    </div>
</div>

app/views/layouts/_message.html.erb
<div class="row d-flex justify-content-center">
    <div class="col-sm-9">
        <div class="alert alert-success alert-dismissible fade show text-center" role="alert">
        <i class="bi-check-circle-fill" ></i>
        <%= notice %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SchoolBasic</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">

  </head>

  <body>
      <% cache do %> 
        <%= render 'layouts/header' %>
      <% end %> 

      <%= render 'layouts/info' if info %>
      <%= render 'layouts/message' if notice %>
      <%= render 'layouts/alert' if alert %> 
      
      <div class="my-5">
        <%= yield %>
      </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  </body>
</html>

app/views/profiles/_form.html.erb
 <div class="container col-lg-6 my-4">
    <div class="card shadow-lg p-3 mb-5 bg-body-tertiary rounded">
        <div class="card-body">
        <div class="row my-2">
          <%= bootstrap_form_with(model: profile) do |form| %>
            <% if profile.errors.any? %>
              <div style="color: red">
                <h5><%= pluralize(profile.errors.count, "error") %> prohibited this profile from being saved:</h5>

                <ul>
                  <% profile.errors.each do |error| %>
                    <li><%= error.full_message %></li>
                  <% end %>
                </ul>
              </div>
            <% end %>

            <div>
              <%= form.text_field :name_profile, 
              label: Profile.human_attribute_name(:name_profile), class: 'text-light-emphasis' %>
              <%= form.select :gender, Profile.genders, {label: :gender}, class: 'text-light-emphasis'%>

              <%= form.select :profile_type, Profile.profile_types, 
                {label: Profile.human_attribute_name(:profile_type)}, class: 'text-light-emphasis' %>
              <%= form.telephone_field :phone1, label: Profile.human_attribute_name(:phone1), 
              class: 'text-light-emphasis' %>
              <%= form.telephone_field :phone2, label: Profile.human_attribute_name(:phone2), 
              class: 'text-light-emphasis' %>
            
              <%= form.collection_select :province_id, Province.order(:province_name), :id, :province_name, 
              { label: Province.model_name.human(count: 1) }, 
              {class:"province province_select text-light-emphasis"} %> 
                
              <%= form.fields_for :address do |address_form| %>
                <%= address_form.collection_select :city_id, cities_array_empty, :id, :city_name, 
                { label: City.model_name.human(count: 1)},  {class:"city_select text-light-emphasis"}%>
                <%= address_form.text_field :street, label: Address.human_attribute_name(:street), 
                class: 'text-light-emphasis' %>
              <% end %> 
              
      
            </div>

            <div class="mb-3 d-grid gap-2">
              <%= form.submit class: "btn btn-info" %>
            </div>
          <% end %>

        </div>
    </div>
  </div>

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>

app/views/profiles/_profile.html.erb
<div class="container col-lg-6 my-4" id="<%= dom_id profile %>" >
  <div class="card shadow-lg p-3 mb-5 bg-body-tertiary rounded">
        <div class="card-body">
     
          <div class="text-center my-2 text-primary-emphasis">
              
              <strong> <%= Profile.human_attribute_name(:gender) %>:</strong> <%= profile.gender %> <br>
              <strong>Email:</strong>  <%= profile.user.email %> <br>
              <strong><%= Profile.human_attribute_name(:profile_type) %>:</strong> <%=  profile.profile_type   %> <br>
              <strong><%= Address.model_name.human(count: 1) %>: </strong> 
                <%= profile.address.street %>, 
                <%= profile.address.city.city_name %>,  
                <%= profile.address.city.province.province_name %>
                <br>
              <strong><%= t(:telephones) %>: </strong> <%= profile.phone1 %>, <%= profile.phone2 %>
  
          </div>
          <div class="mb-3 d-grid gap-2">
              <%= link_to t("links.edit"), edit_profile_path(profile), class: "btn btn-info" %> 
              <% if user_signed_in? %>
                <% if current_user.profile.funcionario? %>
                 <%= button_to "Eliminar", profile, method: :delete, class: "btn btn-danger col-sm-12" %>
                <% end %>
              <% end %>
          </div>
        </div>
    </div>
  </div>
</div>

app/views/profiles/edit.html.erb
<h5 class="text-center">Editar Perfil</h5>
<%= render "form", profile: @profile %>

app/views/profiles/index.html.erb
<h4 class="text-center">Todos perfils</h4>

<div id="profiles">
  <% @profiles.each do |profile| %>
    <%= render profile %>
  <% end %>
</div>

app/views/profiles/new.html.erb
<h4 class="text-center">Novo Perfil</h4>
<%= render "form", profile: @profile %>

app/views/profiles/show.html.erb
<h4 class="text-center">Perfil mostrado</h4>
<%= render @profile %>